version: '3.7'
services:
  nginx.A:
    image: nginx:1.12.2-alpine
    depends_on:
    - nginx.B
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx.A.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
        ipv4_address: 10.1.1.100
  nginx.B:
    image: nginx:1.10.3-alpine
    depends_on:
    - app
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx.B.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
        ipv4_address: 10.1.1.101
  app:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx.app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
        ipv4_address: 10.1.1.102
  wgetter:
    image: alpine
    depends_on:
    - nginx.A
    command: sh -c 'wget -qO /dev/null nginx.A/before; sleep 1; wget -qO /dev/null nginx.A/after; sleep 1; wget -qO /dev/null nginx.B/before; sleep 1; wget -qO /dev/null nginx.B/after'
    networks:
      default:
        ipv4_address: 10.1.1.99

networks:
  default:
    ipam:
      config:
      - subnet: 10.1.1.0/24
